title: "xbreak"
description: "Security researcher, malware critic, etc etc. Just want the soup."

baseurl: "/"
url: "https://AA2958.github.io"

header_pages:
  - index.md
  - whoami.md
  - blog.md
  
footer: 'if (IsDebuggerPresent()) == True { bye(); }'

style: dark # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
